FROM node:20 AS builder
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .

FROM gcr.io/distroless/nodejs22-debian13 AS deployer
WORKDIR /app
COPY --from=builder /app /app
EXPOSE 3000
CMD ["server.js"] #The Google Distroless Node.js image already has its entrypoint set to node
